///|/ Copyright (c) Prusa Research 2023 Enrico Turri @enricoturri1966, Pavel Mikuš @Godrak
///|/
///|/ libvgcode is released under the terms of the AGPLv3 or higher
///|/
#ifndef VGCODE_PATHVERTEX_HPP
#define VGCODE_PATHVERTEX_HPP

#include "Types.hpp"

#include <algorithm>
#include <cfloat>
#include <cmath>

namespace libvgcode {

//
// Struct representating a gcode move (toolpath segment)
//
struct PathVertex
{
    //
    // Segment end position
    //
    Vec3 position{ FLT_MAX, FLT_MAX, FLT_MAX };
    //
    // Segment height
    //
    float height{ 0.0f };
    //
    // Segment width
    //
    float width{ 0.0f };
    //
    // Segment speed
    //
    float feedrate{ 0.0f };
    //
    // Segment actual speed
    //
    float actual_feedrate{ 0.0f };
    //
    // Segment mm3_per_mm
    //
    float mm3_per_mm{ 0.0f };
    //
    // Segment fan speed
    //
    float fan_speed{ 0.0f };
    //
    // Segment temperature
    //
    float temperature{ 0.0f };
#if VGCODE_ENABLE_COG_AND_TOOL_MARKERS
    //
    // Segment weight
    //
    float weight{ 0.0f };
#endif // VGCODE_ENABLE_COG_AND_TOOL_MARKERS
    //
    // Segment extrusion role
    //
    EGCodeExtrusionRole role{ EGCodeExtrusionRole::None };
    //
    // Segment move type
    //
    EMoveType type{ EMoveType::Noop };
    //
    // Segment gcode line id
    //
    uint32_t gcode_id{ 0 };
    //
    // Segment layer id
    //
    uint32_t layer_id{ 0 };
    //
    // Segment extruder id
    //
    uint8_t extruder_id{ 0 };
    //
    // Segment color id
    //
    uint8_t color_id{ 0 };
    //
    // Segment estimated times
    //
    std::array<float, TIME_MODES_COUNT> times{ 0.0f, 0.0f };
    //
    // Layer duration in seconds
    //
    float layer_duration{ 0.0f };
    //
    // ORCA: Add Pressure Advance visualization support
    // Pressure advance value
    //
    float pressure_advance{ 0.0f };
    //
    // ORCA: Add Acceleration visualization support
    // Acceleration value
    //
    float acceleration{ 0.0f };
    //
    // ORCA: Add Jerk visualization support
    // Jerk value
    //
    float jerk{ 0.0f };
    // Orca: Unsupported extrusion width in percent (0 = fully supported, 100 = fully unsupported).
    float overhang_percentage{ 0.0f };
    // Orca: Actual separation of the compared slice planes; old G-code leaves this at zero.
    float overhang_z_distance{ 0.0f };

    // Orca: Convert the contour offset using its slice-plane spacing, which differs from extrusion height
    // when adjacent layers have different thicknesses. Legacy G-code falls back to extrusion height.
    // A fully unsupported line retains the 90-degree convention because its offset has been clamped.
    float overhang_degree() const
    {
        const float percentage = std::clamp(overhang_percentage, 0.0f, 100.0f);
        if (percentage >= 100.0f)
            return 90.0f;
        const float z_distance = overhang_z_distance > 0.0f ? overhang_z_distance : height;
        if (percentage <= 0.0f || width <= 0.0f || z_distance <= 0.0f)
            return 0.0f;

        constexpr float radians_to_degrees = 57.29577951308232f;
        return std::atan(0.01f * percentage * width / z_distance) * radians_to_degrees;
    }

    //
    // Return true if the segment is an extrusion move
    //
    bool is_extrusion() const;
    //
    // Return true if the segment is an travel move
    //
    bool is_travel() const;
    //
    // Return true if the segment is an option
    // See: EOptionType
    //
    bool is_option() const;
    //
    // Return true if the segment is a wipe move
    //
    bool is_wipe() const;
    //
    // Return true if the segment was generated by custom gcode
    //
    bool is_custom_gcode() const;
    //
    // Return the volumetric flow rate of the segment
    //
    float volumetric_rate() const { return feedrate * mm3_per_mm; }
    //
    // Return the acutal volumetric flow rate of the segment
    //
    float actual_volumetric_rate() const { return actual_feedrate * mm3_per_mm; }

    static const PathVertex DUMMY_PATH_VERTEX;
};

} // namespace libvgcode

#endif // VGCODE_PATHVERTEX_HPP
